### ISSUE TITLE
Please approve puppet/erlang

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet-approved-modules#4]
## Puppet Module Approval Request

 - [x] I can confirm I have checked my module against the [Approved module criteria](https://forge.puppet.com/about/approved/criteria) and I think it is a suitable candidate.

Please include the module Github URL *(include namespace and module name)*,
**For example**: https://github.com/voxpupuli/puppet-erlang

Gareth made an erlang module ages ago. it has the approved badge, but wasn't updated in 8 years: https://forge.puppet.com/modules/garethr/erlang/readme

I think this doesn't quafily anymore for the approved badge and it should be transferred to the Vox Pupuli module.

**Comment by david22swan** [comment]
1. Style - Module is well laid out and easily understood
2. Documentation - README is relatively sparse and does not have any example usage, the REFERENCE does however so I would personally consider this requirement fulfilled.
3. Maintenance and Lifecycle - Module seems to be actively maintained with multiple maintenance commits through the past 6 months. Module has a handful of maintainers, with the added knowledge of this being a Vox module I am happy with this.
4. License - Module is licensed under Apache
5. Originality - While, as stated above, there already exists a approved module with the same functionality, it has not been updated since 2014, as such I would feel confident in moving the approval to this module.
6. Metadata - metadata looks clean and accurate
7. semver - Module has been tagged with semver
8. Testing - module features good test coverage, though on a PR basis only, no nightly test coverage in place. Due to the rather static nature of the module this is not a large issue however.
9. Puppet Version - Module is up to date with current puppet versions

**Comment by david22swan** [comment]
@bastelfreak This all look's good to me, will talk it over but I think we are good to get this approved.

**Comment by david22swan** [comment]
@bastelfreak That's the badge transferred over now
